# Generated by Django 4.2.7 on 2024-03-17 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import servicios.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentMethod', models.TextField(choices=[('Efectivo', 'Efectivo'), ('Nequi', 'Nequi'), ('Daviplata', 'Daviplata'), ('Mastercard', 'Mastercard'), ('Visa', 'Visa')], null=True, verbose_name='Metodo De Pago')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'db_table': 'ingresos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_cliente', models.EmailField(blank=True, editable=False, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('numberPhone', models.BigIntegerField(null=True, verbose_name='Numero de celular')),
                ('dateOT', models.DateField(validators=[servicios.models.no_past_dates_validators], verbose_name='Fecha entrada')),
                ('totalPrice', models.FloatField(blank=True, null=True, verbose_name='Valor Total')),
                ('nombre_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_jobs_cliente', to=settings.AUTH_USER_MODEL, verbose_name='Nombre del Cliente')),
                ('paymentMethod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_jobs_payment_method', to='servicios.income', verbose_name='Método de Pago')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Ordenes de trabajo',
                'db_table': 'orden_trabajo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(null=True, verbose_name='Cantidad Producto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripcion Producto')),
                ('status', models.CharField(choices=[('Manchado', 'Manchado'), ('Roto', 'Roto'), ('Quemado', 'Quemado'), ('Decolorado', 'Decolorado'), ('Ninguno', 'Ninguno')], max_length=255, verbose_name='Estado del producto')),
                ('category', models.CharField(choices=[('Camisa', 'Camisa'), ('Pantalon', 'Pantalon'), ('Sudadera', 'Sudadera'), ('Chaqueta', 'Chaqueta'), ('Zapatos', 'Zapatos'), ('Traje', 'Traje'), ('Peluches', 'Peluches'), ('Alfombra', 'Alfombra'), ('Muebles', 'Muebles'), ('Sueter', 'Sueter'), ('Camiseta', 'Camiseta')], max_length=255, verbose_name='Categoria del Producto')),
            ],
            options={
                'verbose_name': 'Listado de Producto',
                'verbose_name_plural': 'Listado de Productos',
                'db_table': 'listado_producto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TypeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptionTS', models.CharField(blank=True, choices=[('Lavanderia', 'Lavanderia'), ('Tintoreria', 'Tintoreria'), ('Lavado especial', 'Lavado especial')], max_length=255, null=True, verbose_name='Descripcion')),
                ('value', models.FloatField(default=0.0, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Tipo de Servicio',
                'verbose_name_plural': 'Tipos de Servicio',
                'db_table': 'tipo_de_servicio',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OutputOJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountOutputs', models.IntegerField(null=True, verbose_name='Cantidad Salidas')),
                ('dateOutput', models.DateField(null=True, validators=[servicios.models.no_past_dates_validators], verbose_name='Fecha salida')),
                ('orderJob', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.orderjob', verbose_name='Orden de Trabajo')),
            ],
            options={
                'verbose_name': 'Salida OT',
                'verbose_name_plural': 'Salidas OT',
                'db_table': 'salidas_ot',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='orderjob',
            name='productList',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_jobs_product', to='servicios.productlist', verbose_name='Listado de Productos'),
        ),
        migrations.AddField(
            model_name='orderjob',
            name='typeService',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_jobs_type_service', to='servicios.typeservice', verbose_name='Tipo de Servicio'),
        ),
    ]
