# Generated by Django 4.2.7 on 2023-12-11 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(blank=True, null=True, verbose_name='Inicio Horario')),
                ('finalDate', models.DateField(blank=True, null=True, verbose_name='Fin Horario')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'db_table': 'horario',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailSalary', models.TextField(blank=True, null=True, verbose_name='Detalle salario')),
                ('descriptionAccount', models.TextField(blank=True, null=True, verbose_name='Descripcion Ingresos')),
                ('numberAccount', models.IntegerField(blank=True, null=True, verbose_name='Numero de Cuenta')),
                ('totalSalary', models.IntegerField(verbose_name='Total salario')),
                ('activities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='actividades.activity')),
                ('schedules', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionHumana.schedule')),
            ],
            options={
                'verbose_name': 'Salario',
                'verbose_name_plural': 'Salarios',
                'db_table': 'sueldo',
                'ordering': ['id'],
            },
        ),
    ]
