# Generated by Django 4.2.7 on 2023-12-11 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPrice', models.CharField(blank=True, max_length=255, null=True, verbose_name='Valor Total')),
                ('dateOT', models.DateField(blank=True, null=True, verbose_name='Fecha entrada')),
                ('amountOT', models.CharField(max_length=255, verbose_name='Cantidad')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Ordenes de trabajo',
                'db_table': 'orden_trabajo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TypeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptionTS', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripcion')),
                ('orderJob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.orderjob')),
            ],
            options={
                'verbose_name': 'Tipo de Servicio',
                'verbose_name_plural': 'Tipos de Servicio',
                'db_table': 'tipo_de_servicio',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptionProduct', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripcion Producto')),
                ('orderJob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.orderjob')),
            ],
            options={
                'verbose_name': 'Estado del Producto',
                'verbose_name_plural': 'Estados del Producto',
                'db_table': 'estado_producto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountProduct', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cantidad Producto')),
                ('descriptionProduct', models.TextField(blank=True, null=True, verbose_name='Descripcion Producto')),
                ('statusProduct', models.CharField(max_length=255, verbose_name='Estado del producto')),
                ('categoryProduct', models.CharField(max_length=255, verbose_name='Categoria del Producto')),
                ('orderJob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.orderjob')),
            ],
            options={
                'verbose_name': 'Listado de Producto',
                'verbose_name_plural': 'Listados de Producto',
                'db_table': 'listado_producto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OutputOJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountOutputs', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cantidad Salidas')),
                ('dateOutput', models.DateField(blank=True, null=True, verbose_name='Fecha salida')),
                ('productList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.productlist')),
            ],
            options={
                'verbose_name': 'Salida OT',
                'verbose_name_plural': 'Salidas OT',
                'db_table': 'salidas_ot',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentMethod', models.TextField(blank=True, null=True, verbose_name='Metodo De Pago')),
                ('descriptionIncome', models.TextField(blank=True, null=True, verbose_name='Descripcion Ingresos')),
                ('totalincome', models.CharField(max_length=255, verbose_name='Total ingresos')),
                ('orderJob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.orderjob')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'db_table': 'ingresos',
                'ordering': ['id'],
            },
        ),
    ]
