# Generated by Django 4.2.7 on 2024-03-17 08:06

import actividades.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novelty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateN', models.DateField(verbose_name='Fecha de la Novedad')),
                ('stateN', models.CharField(choices=[('Manchado', 'Manchado'), ('Roto', 'Roto'), ('Quemado', 'Quemado'), ('Decolorado', 'Decolorado'), ('Ninguno', 'Ninguno')], max_length=50, verbose_name='Estado Novedad')),
            ],
            options={
                'verbose_name': 'Novedad',
                'verbose_name_plural': 'Novedades',
                'db_table': 'novedad',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StateAc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stateAc', models.CharField(choices=[('Realizada', 'Realizada'), ('En proceso', 'En proceso'), ('Pendiente', 'Pendiente')], max_length=200, verbose_name='Estado de las Actividades')),
            ],
            options={
                'verbose_name': 'EstadoAc',
                'verbose_name_plural': 'EstadosAc',
                'db_table': 'estadosac',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAc', models.DateField(validators=[actividades.models.no_past_dates_validators], verbose_name='Fecha Actividad')),
                ('timeAc', models.TimeField(null=True, verbose_name='Tiempo de desarrollo actividad')),
                ('descriptionAc', models.TextField(verbose_name='Descripción Actividad')),
                ('amountToUse', models.IntegerField(null=True, validators=[actividades.models.no_negative_values_validator], verbose_name='Cantidad de Insumo a utilizar')),
                ('ActivityValue', models.FloatField(verbose_name='Valor actividad')),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.input', verbose_name='Insumo')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.machine', verbose_name='Maquina')),
                ('noveltyAc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.novelty', verbose_name='Novedad de la Actividad')),
                ('orderJob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.orderjob', verbose_name='orden de trabajo')),
                ('stateAc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.stateac', verbose_name='Estado de Actividad')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'db_table': 'actividades',
                'ordering': ['id'],
            },
        ),
    ]
