# Generated by Django 4.2.7 on 2024-03-17 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_nameI', models.CharField(max_length=50, verbose_name='Nombre proveedor')),
                ('amountI', models.IntegerField(verbose_name='Cantidad')),
                ('product_type', models.CharField(max_length=20, verbose_name='Tipo insumo')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'db_table': 'insumo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_nameM', models.CharField(max_length=50, verbose_name='Nombre proveedor')),
                ('amountM', models.IntegerField(verbose_name='Cantidad')),
                ('machine_type', models.CharField(max_length=20, verbose_name='Tipo maquina')),
                ('description', models.TextField(verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Maquina',
                'verbose_name_plural': 'Maquinas',
                'db_table': 'maquina',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Input_product', to='inventario.input', verbose_name='Insumos')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Machine_product', to='inventario.machine', verbose_name='Maquinas')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'inventario',
                'ordering': ['id'],
            },
        ),
    ]
