# Generated by Django 4.2.6 on 2023-11-08 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novelty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateN', models.DateField(verbose_name='Fecha de la Novedad')),
                ('descriptionN', models.TextField(verbose_name='Descripción Novedad')),
                ('stateN', models.CharField(max_length=50, verbose_name='Estado Novedad')),
            ],
            options={
                'verbose_name': 'Novedad',
                'verbose_name_plural': 'Novedades',
                'db_table': 'novedad',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StateAc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stateAc', models.CharField(max_length=200, verbose_name='Estado de las Actividades')),
            ],
            options={
                'verbose_name': 'EstadoAc',
                'verbose_name_plural': 'EstadosAc',
                'db_table': 'estadosac',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAc', models.DateField(verbose_name='Fecha Actividad')),
                ('timeAc', models.DurationField(blank=True, null=True, verbose_name='Tiempo de desarrollo actividad')),
                ('descriptionAc', models.TextField(verbose_name='Descripción Actividad')),
                ('orderJob', models.IntegerField(verbose_name='Orden de trabajo')),
                ('inventory', models.IntegerField(verbose_name='Inventario')),
                ('salary', models.IntegerField(verbose_name='Salario')),
                ('noveltyAc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.novelty')),
                ('stateAc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.stateac')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'db_table': 'actividades',
                'ordering': ['id'],
            },
        ),
    ]
