# Generated by Django 4.2.6 on 2023-11-01 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=20, verbose_name='Tipo Producto')),
                ('description', models.TextField(verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_type', models.CharField(max_length=20, verbose_name='Tipo maquina')),
                ('description', models.TextField(verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=50, verbose_name='Nombre proveedor')),
                ('amount', models.FloatField(verbose_name='Cantidad')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.input')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.machine')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'inventario',
                'ordering': ['id'],
            },
        ),
    ]
