# Generated by Django 4.2.6 on 2023-11-01 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='input',
            options={'ordering': ['id'], 'verbose_name': 'Insumo', 'verbose_name_plural': 'Insumos'},
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['id'], 'verbose_name': 'Maquina', 'verbose_name_plural': 'Maquinas'},
        ),
        migrations.AlterModelTable(
            name='input',
            table='insumo',
        ),
        migrations.AlterModelTable(
            name='machine',
            table='maquina',
        ),
    ]
